## Motivation

Every two years, every member of the United States House of Representatives is up for election. After being elected, members of the House are given a set budget from the legislature itself to hire staff, buy office equipment, and defray other costs of legislating and addressing constituent concerns. While each office gets the same amount of money from Congress to spend on these purposes, congressional offices have discretion over how that allowance is actually spent, and we would like to see whether some spending patterns are associated with higher political success. 

# Part 1: Getting/Formatting the Data

For this project, we decided to use the [House Office Expenditure Data](https://www.propublica.org/datastore/dataset/house-office-expenditures) from ProPublica as it contains well formatted data about house expenditures from 2009 to 2018. The main downside of this dataset is that it is missing data from the most recent midterm election, but we still have almost 10 years of data to work with.

To programatically access the datasets we are working with, we have included copies here [repository](https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/).

In [1]:
import pandas as pd
# just finna test with one of the files to see what happens
frames = []
# #manually add stuff for 2009 since only Q3 and Q4 are present
# frames.append(pd.read_csv('https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/2009Q3-house-disburse-detail.csv').dropna(subset = ['BIOGUIDE_ID']))
# frames.append(pd.read_csv('https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/2009Q4-house-disburse-detail.csv').dropna(subset = ['BIOGUIDE_ID']))


#automate the dataframes from 2010 to 2017
for i in range(2015, 2019):
    for j in range(1, 5):
        df = pd.read_csv('https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/' + str(i) + 'Q' + str(j) +'-house-disburse-detail.csv', thousands=',')
        df.dropna(subset = ['BIOGUIDE_ID'], inplace=True)
        df["QUARTER"] = str(i) + 'Q' + str(j)#df.apply(lambda row: str(i) + 'Q' + str(j))
        df["YEAR"] = i
        frames.append(df)

house_data = pd.concat(frames)
house_data

/tmp/ipykernel_2909/1279218428.py:12: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/' + str(i) + 'Q' + str(j) +'-house-disburse-detail.csv', thousands=',')


BIOGUIDE_ID                   OFFICE QUARTER                   CATEGORY  \
5565      A000374       HON. RALPH ABRAHAM  2015Q1               FRANKED MAIL   
5566      A000374       HON. RALPH ABRAHAM  2015Q1               FRANKED MAIL   
5567      A000374       HON. RALPH ABRAHAM  2015Q1               FRANKED MAIL   
5568      A000374       HON. RALPH ABRAHAM  2015Q1               FRANKED MAIL   
5569      A000374       HON. RALPH ABRAHAM  2015Q1               FRANKED MAIL   
...           ...                      ...     ...                        ...   
86322     Z000017  2016 HON. LEE M. ZELDIN  2018Q4  PRINTING AND REPRODUCTION   
86323     Z000017  2015 HON. LEE M. ZELDIN  2018Q4     SUPPLIES AND MATERIALS   
86324     Z000017  2015 HON. LEE M. ZELDIN  2018Q4     SUPPLIES AND MATERIALS   
86325     Z000017  2015 HON. LEE M. ZELDIN  2018Q4     SUPPLIES AND MATERIALS   
86326     Z000017  2015 HON. LEE M. ZELDIN  2018Q4     SUPPLIES AND MATERIALS   

             DATE                              PAYEE  START DATE    END DATE  \
5565        01-31                                NaN    01/20/15    01/31/15   
5566        02-27       UNITED STATES POSTAL SERVICE    01/03/15    01/31/15   
5567        02-28                                NaN    02/20/15    02/28/15   
5568        03-26       UNITED STATES POSTAL SERVICE    02/01/15    02/28/15   
5569        03-31                                NaN    03/20/15    03/31/15   
...           ...                                ...         ...         ...   
86322                                                                          
86323  2018-10-18  CITI PCARD-MEDALSOFAMERICA/PATRIO  2015-08-29  2015-09-28   
86324                                                                          
86325                                                                          
86326                                                                          

                                    PURPOSE  AMOUNT  ...     TRANSCODELONG  \
5565                           FRANKED MAIL  -15.15  ...    General ledger   
5566                           FRANKED MAIL   35.89  ...  Accounts payable   
5567                           FRANKED MAIL  -21.30  ...    General ledger   
5568                           FRANKED MAIL  222.30  ...  Accounts payable   
5569                           FRANKED MAIL  -67.55  ...    General ledger   
...                                     ...     ...  ...               ...   
86322                       OFFICE TOTALS:   291.21  ...               NaN   
86323             OFFICE SUPPLIES (OUTSIDE)   52.40  ...               NaN   
86324        SUPPLIES AND MATERIALS TOTALS:   52.40  ...               NaN   
86325  OFFICIAL EXPENSES OF MEMBERS TOTALS:   52.40  ...               NaN   
86326                       OFFICE TOTALS:    52.40  ...               NaN   

         RECORDID                 RECIP (orig.)                       PROGRAM  \
5565   FLG0046204                           NaN                           NaN   
5566     00778764  UNITED STATES POSTAL SERVICE                           NaN   
5567   FLG0046943                           NaN                           NaN   
5568     00784273  UNITED STATES POSTAL SERVICE                           NaN   
5569   FLG0047807                           NaN                           NaN   
...           ...                           ...                           ...   
86322                                       NaN  OFFICIAL EXPENSES OF MEMBERS   
86323     1028651                           NaN  OFFICIAL EXPENSES OF MEMBERS   
86324                                       NaN  OFFICIAL EXPENSES OF MEMBERS   
86325                                       NaN  OFFICIAL EXPENSES OF MEMBERS   
86326                                       NaN  OFFICIAL EXPENSES OF MEMBERS   

                      SORT SEQUENCE SORT SUBTOTAL DESCRIPTION  \
5565                            NaN                       NaN   
5566                            

[election data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2)

In [2]:
election_data = pd.read_csv('https://github.com/AndrewTrackim/cmsc320-final/raw/master/house-expenditure/1976-2020-house.csv')

# filter out the years before 2009 and after 2018
election_data = election_data[election_data['year'] >= 2009]
election_data = election_data[election_data['year'] <= 2018]

#split candidate names into first and last
election_data['first_name'] = election_data['candidate'].apply(lambda x: x.split(' ')[0])
election_data['last_name'] = election_data['candidate'].apply(lambda x: x.split(' ')[-1])

election_data

year    state state_po  state_fips  state_cen  state_ic    office  \
22553  2010  ALABAMA       AL           1         63        41  US HOUSE   
22554  2010  ALABAMA       AL           1         63        41  US HOUSE   
22555  2010  ALABAMA       AL           1         63        41  US HOUSE   
22556  2010  ALABAMA       AL           1         63        41  US HOUSE   
22557  2010  ALABAMA       AL           1         63        41  US HOUSE   
...     ...      ...      ...         ...        ...       ...       ...   
29631  2018  WYOMING       WY          56         83        68  US HOUSE   
29632  2018  WYOMING       WY          56         83        68  US HOUSE   
29633  2018  WYOMING       WY          56         83        68  US HOUSE   
29634  2018  WYOMING       WY          56         83        68  US HOUSE   
29635  2018  WYOMING       WY          56         83        68  US HOUSE   

       district stage runoff  ...         party writein   mode  \
22553         1   GEN    NaN  ...  CONSTITUTION   False  TOTAL   
22554         1   GEN    NaN  ...    REPUBLICAN   False  TOTAL   
22555         1   GEN    NaN  ...           NaN    True  TOTAL   
22556         2   GEN    NaN  ...      DEMOCRAT   False  TOTAL   
22557         2   GEN    NaN  ...    REPUBLICAN   False  TOTAL   
...         ...   ...    ...  ...           ...     ...    ...   
29631         0   GEN    NaN  ...  CONSTITUTION   False  TOTAL   
29632         0   GEN    NaN  ...      DEMOCRAT   False  TOTAL   
29633         0   GEN    NaN  ...    REPUBLICAN   False  TOTAL   
29634         0   GEN    NaN  ...   LIBERTARIAN   False  TOTAL   
29635         0   GEN    NaN  ...           NaN    True  TOTAL   

       candidatevotes totalvotes  unofficial   version  fusion_ticket  \
22553           26357     156281       False  20220331          False   
22554          129063     156281       False  20220331          False   
22555             861     156281       False  20220331          False   
22556          106865     219028       False  20220331          False   
22557          111645     219028       False  20220331          False   
...               ...        ...         ...       ...            ...   
29631            6070     201245       False  20220331          False   
29632           59903     201245       False  20220331          False   
29633          127963     201245       False  20220331          False   
29634            6918     201245       False  20220331          False   
29635             391     201245       False  20220331          False   

       first_name  last_name  
22553       DAVID     WALTER  
22554          JO     BONNER  
22555     WRITEIN    WRITEIN  
22556       BOBBY     BRIGHT  
22557      MARTHA       ROBY  
...           ...        ...  
29631      DANIEL   CUMMINGS  
29632        GREG     HUNTER  
29633         LIZ     CHENEY  
29634     RICHARD   BRUBAKER  
29635     WRITEIN    WRITEIN  

[7083 rows x 22 columns]

Try to figure out what categories we are working with and how these categories should be group into broader categories

In [3]:
from collections import defaultdict
categories = defaultdict(lambda: 0)
def add_set(row):
      categories[row['CATEGORY']] += 1

#apply add_set to the house_data
house_data.apply(add_set, axis = 1);
categories

defaultdict(<function __main__.<lambda>()>,
            {'FRANKED MAIL': 41809,
             'PERSONNEL COMPENSATION': 159047,
             'TRAVEL': 292973,
             'RENT, COMMUNICATION, UTILITIES': 139961,
             'PRINTING AND REPRODUCTION': 55142,
             'OTHER SERVICES': 61435,
             'SUPPLIES AND MATERIALS': 227999,
             'EQUIPMENT': 41185,
             'TRANSPORTATION OF THINGS': 355,
             'PERSONNEL BENEFITS': 8,
             'RENT COMMUNICATION UTILITIES': 18459,
             'RENT  COMMUNICATION  UTILITIES': 129425,
             'BENEFITS TO FORMER PERSONNEL': 5,
             nan: 84545})

In [4]:
replace = {
    'RENT  COMMUNICATION  UTILITIES': 'RENT, COMMUNICATION, UTILITIES',
    'RENT COMMUNICATION UTILITIES': 'RENT, COMMUNICATION, UTILITIES'
}
house_data.replace(to_replace=replace, value=None, inplace=True)
categories = defaultdict(lambda: 0)
def add_set(row):
      categories[row['CATEGORY']] += 1
      
house_data.apply(add_set, axis = 1);
categories

defaultdict(<function __main__.<lambda>()>,
            {'FRANKED MAIL': 41809,
             'PERSONNEL COMPENSATION': 159047,
             'TRAVEL': 292973,
             'RENT, COMMUNICATION, UTILITIES': 139961,
             'PRINTING AND REPRODUCTION': 55142,
             'OTHER SERVICES': 61435,
             'SUPPLIES AND MATERIALS': 227999,
             'EQUIPMENT': 41185,
             'TRANSPORTATION OF THINGS': 355,
             'PERSONNEL BENEFITS': 8,
             'RENT COMMUNICATION UTILITIES': 18459,
             'RENT  COMMUNICATION  UTILITIES': 129425,
             'BENEFITS TO FORMER PERSONNEL': 5,
             nan: 84545})

In [5]:
import numpy as np
quarters = house_data['QUARTER'].unique()
categories = house_data['CATEGORY'].unique()

quarter = quarters[0]
hd_by_quarter = house_data[house_data['QUARTER'] == quarter]
bio_ids = hd_by_quarter['BIOGUIDE_ID'].unique()


spending_per_candidate = hd_by_quarter.groupby(['BIOGUIDE_ID','CATEGORY'])['AMOUNT'].sum()
spending_data = []
for bio_id in bio_ids:
    row = [bio_id]
    for category in categories:
        if category in spending_per_candidate[bio_id]:
            row.append(spending_per_candidate[bio_id][category])
        else:
            row.append(np.nan)
    spending_data.append(row)
quarter_spending_df = pd.DataFrame(spending_data,columns = ["BIOGUIDE_ID"] + categories.tolist())
quarter_spending_df
# spending_per_candidate.to_csv('spending_per_candidate_' + quarter + '.csv')

BIOGUIDE_ID  FRANKED MAIL  PERSONNEL COMPENSATION    TRAVEL  \
0       A000374        154.19               165171.51  23318.33   
1       A000370         94.91               169131.98   8734.71   
2       A000055       1455.81               233308.09  13219.96   
3       A000371       -108.11               133936.12  19023.61   
4       A000372        599.20               184178.06  14749.44   
..          ...           ...                     ...       ...   
501     Y000066        869.14               157710.79   6574.15   
502     Y000033        645.22               255064.41  16005.45   
503     Y000064       1425.58               233500.61  11762.09   
504     Z000017          2.85               208474.87       NaN   
505     Z000018        -27.57               183531.15  15864.42   

     RENT, COMMUNICATION, UTILITIES  PRINTING AND REPRODUCTION  \
0                          20132.91                    2623.14   
1                          34509.98                    6993.02   
2                          25663.84                    2736.66   
3                          16389.06                    1752.20   
4                          10592.15                    2420.91   
..                              ...                        ...   
501                        23756.48                    2674.30   
502                        23820.85                     424.59   
503                        18076.64                    1714.11   
504                        16145.23                     162.40   
505                        13808.45                    1495.43   

     OTHER SERVICES  SUPPLIES AND MATERIALS  EQUIPMENT  \
0           8379.35                21927.03        NaN   
1           6184.00                11458.44    1284.70   
2           5686.53                19519.09   18743.53   
3           7728.26                11926.93    1979.40   
4           9087.25                13015.72     437.10   
..              ...                     ...        ...   
501        11106.78                 4634.97    1372.37   
502        11290.00                10082.29     180.89   
503         7865.47                 4676.80   11481.00   
504        21807.00                 3331.53     813.31   
505         6317.66                 6236.12     747.71   

     TRANSPORTATION OF THINGS  PERSONNEL BENEFITS  \
0                         NaN                 NaN   
1                         NaN                 NaN   
2                         NaN                 NaN   
3                         NaN                 NaN   
4                         NaN                 NaN   
..                        ...                 ...   
501                       NaN                 NaN   
502                       NaN                 NaN   
503                       NaN                 NaN   
504                       NaN                 NaN   
505                       NaN                 NaN   

     RENT COMMUNICATION UTILITIES  RENT  COMMUNICATION  UTILITIES  \
0                             NaN                             NaN   
1                             NaN                             NaN   
2                             NaN                             NaN   
3                             NaN                             NaN   
4                             NaN                             NaN   
..                            ...                             ...   
501                           NaN                             NaN   
502                           NaN                             NaN   
503                           NaN                             NaN   
504                           NaN                             NaN   
505                           NaN                             NaN   

     BENEFITS TO FORMER PERSONNEL  NaN  
0                             NaN  NaN  
1                             NaN  NaN  
2                             NaN  NaN  
3                             NaN  NaN  
4                             NaN  NaN

## Predicting Election Results

We can see if there is some correlation between the proportions that senators spend on each category and whether or not they get re-elected. We can possibly use this to make a predictor for whether or not a person will get reelected.

To make a regression of this data, I will need to have a column for each type of expenditure. I will do this by summing up each category of expense by YEAR and BUIOGUIDE_ID.

# THIS BLOCK IS DUPLICATE FROM ARJUN BRANCH

In [6]:
import requests
from bs4 import BeautifulSoup
raw = requests.get("https://www.congress.gov/help/field-values/member-bioguide-ids")
soup = BeautifulSoup(raw.text, 'lxml')
table = soup.find('table')

# Since the entire thing is a formatted table, read it directly into a pandas dataframe
tabledf = pd.read_html(str(table))
tabledf = tabledf[0]
tabledf.dropna(subset = ['Member'], inplace=True)
tabledf.reset_index(drop=True, inplace=True)
members = tabledf['Member'].str.extractall("(.*), (.*) \((.*) - (.*)\)")

members.reset_index(drop=True, inplace=True)
members.rename(columns={0 : 'LASTNAME', 1: "FIRSTNAME", 2: "PARTY", 3: "STATE"}, inplace=True)
members['BIOGUIDE_ID'] = tabledf['Member ID']
members['LASTNAME'] = members['LASTNAME'].apply(lambda x: x.upper())
members['FIRSTNAME'] = members['FIRSTNAME'].apply(lambda x: x.split(' ')[0].upper())
members

LASTNAME FIRSTNAME       PARTY         STATE BIOGUIDE_ID
0          ABDNOR     JAMES  Republican  South Dakota     A000009
1     ABERCROMBIE      NEIL  Democratic        Hawaii     A000014
2        ABOUREZK     JAMES  Democratic  South Dakota     A000017
3         ABRAHAM     RALPH  Republican     Louisiana     A000374
4         ABRAHAM   SPENCER  Republican      Michigan     A000355
...           ...       ...         ...           ...         ...
2422        ZINKE      RYAN  Republican       Montana     Z000018
2423         ZION     ROGER  Republican       Indiana     Z000010
2424     ZORINSKY    EDWARD  Democratic      Nebraska     Z000013
2425       ZSCHAU     EDWIN  Republican    California     Z000014
2426        ZWACH      JOHN  Republican     Minnesota     Z000016

[2427 rows x 5 columns]

In [7]:
years = house_data['YEAR'].unique()
categories = house_data['CATEGORY'].unique()

year = years[0]



spending_per_candidate = house_data.groupby(['YEAR', 'BIOGUIDE_ID','CATEGORY'])['AMOUNT'].sum()

spending_data = []
for year in years:
    for bio_id in bio_ids:
        # set the row to be the bio_id and year
        if bio_id in spending_per_candidate[year]:
            row = [bio_id, year]
            for category in categories:
                if category in spending_per_candidate[year][bio_id]:
                    row.append(spending_per_candidate[year][bio_id][category])
                else:
                    row.append(np.nan)
            spending_data.append(row)

year_spending_df = pd.DataFrame(spending_data,columns = ["BIOGUIDE_ID", "YEAR"] + categories.tolist())

# replace the NaNs with 0
year_spending_df.fillna(0, inplace=True)
year_spending_df

# combine totals for years into pairs of two

BIOGUIDE_ID  YEAR  FRANKED MAIL  PERSONNEL COMPENSATION     TRAVEL  \
0        A000374  2015      47342.30               838124.23  119448.98   
1        A000370  2015      15742.82               804980.56   60240.36   
2        A000055  2015       9764.00               910757.11   72235.60   
3        A000371  2015      29241.73               727250.21   64116.39   
4        A000372  2015      40044.59               838910.12   58196.76   
...          ...   ...           ...                     ...        ...   
1810     Y000065  2018      45589.00              1350727.62   77260.00   
1811     Y000066  2018      52795.42              1538359.38  111500.80   
1812     Y000033  2018       1557.96              1745761.90  217851.52   
1813     Z000017  2018     110893.14              1507166.60   49663.32   
1814     Z000018  2018          0.00                    0.00       0.00   

      RENT, COMMUNICATION, UTILITIES  PRINTING AND REPRODUCTION  \
0                           81221.99                   42381.64   
1                          104481.00                   29949.28   
2                           93374.57                    8340.59   
3                          127959.03                   96840.62   
4                           62637.48                   54869.03   
...                              ...                        ...   
1810                            0.00                   74791.20   
1811                            0.00                   44553.60   
1812                            0.00                    2684.42   
1813                            0.00                   87864.66   
1814                            0.00                     225.08   

      OTHER SERVICES  SUPPLIES AND MATERIALS   EQUIPMENT  \
0           37351.59                38574.56    12888.87   
1           27040.57                26028.37    86724.37   
2           28794.12                38245.97    35383.90   
3           31022.73                39300.14    12316.56   
4           48957.25                28710.84     2006.61   
...              ...                     ...         ...   
1810        83745.12                48722.86  1858767.46   
1811        63654.00                56829.10  2091764.10   
1812        72260.00                40343.26  2238730.54   
1813       124853.10               106987.42  2025446.82   
1814            0.00                    0.00        0.00   

      TRANSPORTATION OF THINGS  PERSONNEL BENEFITS  \
0                        40.00                 0.0   
1                         0.00                 0.0   
2                         0.00                 0.0   
3                         0.00                 0.0   
4                         0.00                 0.0   
...                        ...                 ...   
1810                      0.00                 0.0   
1811                      0.00                 0.0   
1812                      0.00                 0.0   
1813                    107.28                 0.0   
1814                      0.00                 0.0   

      RENT COMMUNICATION UTILITIES  RENT  COMMUNICATION  UTILITIES  \
0                              0.0                            0.00   
1                              0.0                            0.00   
2                              0.0                            0.00   
3                              0.0                            0.00   
4                              0.0                            0.00   
...                            ...                             ...   
1810                           0.0                       168570.94   
1811                           0.0                       182881.44   
1812                           0.0                       137979.40   
1813                           0.0                       176797.62   
1814                           0.0                            0.00   

      BENEFITS TO FORMER PERSONNEL  NaN  
0                              0.0  0.0  
1   

Since house elections only happen every 2 years, I will sum up adjacent years prior to an election for the sake of this regression. For example, the data for 2017 and 2018 will be added and categorized as 2018 since those are the years after the 2016 election but (mostly) before the 2018 elections.

In [8]:
parts = []

def helper(x):
    years = house_data['YEAR'].unique()
    # add together the first two years  
    if years[0] % 2 == 1:
        start = 0
    else:
        start = 1
    #add together the first 2 columns of x
    for i in range(start, len(years), 2):
        # sum together the money amoutns for the two years
        row = x[i:i+2].sum()

        #fix bioguide id and year since those also got summed
        row['YEAR'] = int(years[i+1])
        row['BIOGUIDE_ID'] = x[0:1]["BIOGUIDE_ID"].values[0]

        # add together all the other columns and then change values to proportions
        sum = 0
        for category in categories:
            sum += row[category]

        # now calculate the proportions
        success = True
        for category in categories:
            if sum != 0:
                row[category] = row[category] / sum
            else:
                success = False
        
        # if the sum is 0, then they weren't in office for the years so they shouldn't be included
        if success:
            parts.append(row)
        
        # Now check whether or not they won the election for that year
            
year_spending_df.groupby('BIOGUIDE_ID').apply(helper)
merged_years_df = pd.DataFrame(parts)

# add party and name info
merged_years_df = merged_years_df.merge(members, on='BIOGUIDE_ID')
merged_years_df

BIOGUIDE_ID  YEAR  FRANKED MAIL  PERSONNEL COMPENSATION    TRAVEL  \
0       A000055  2016      0.006792                0.759666  0.062165   
1       A000055  2018      0.003452                0.411295  0.038683   
2       A000210  2016      0.000000                0.000000  0.000000   
3       A000367  2016      0.001191                0.845177  0.027990   
4       A000367  2018      0.000342                0.436474  0.015704   
..          ...   ...           ...                     ...       ...   
943     Y000066  2018      0.011930                0.383713  0.027440   
944     Z000017  2016      0.057046                0.734275  0.020706   
945     Z000017  2018      0.019922                0.388718  0.014518   
946     Z000018  2016      0.034226                0.725436  0.106587   
947     Z000018  2018      0.000739                0.464566  0.024899   

     RENT, COMMUNICATION, UTILITIES  PRINTING AND REPRODUCTION  \
0                          0.067225                   0.007137   
1                          0.000000                   0.003279   
2                         -1.014942                   0.000000   
3                          0.064083                   0.002848   
4                          0.000000                   0.001546   
..                              ...                        ...   
943                        0.000000                   0.009136   
944                        0.073223                   0.045088   
945                        0.000000                   0.017221   
946                        0.046623                   0.031469   
947                        0.000000                   0.005774   

     OTHER SERVICES  SUPPLIES AND MATERIALS  EQUIPMENT  \
0          0.023548                0.036877   0.026836   
1          0.009586                0.011584   0.480641   
2          0.104496                0.002897   1.907549   
3          0.030233                0.011010   0.010840   
4          0.013726                0.013396   0.476682   
..              ...                     ...        ...   
943        0.021860                0.011933   0.485055   
944        0.040390                0.012667   0.004211   
945        0.024321                0.016703   0.472676   
946        0.025858                0.010062   0.011522   
947        0.029243                0.343804   0.072409   

     TRANSPORTATION OF THINGS  PERSONNEL BENEFITS  \
0                0.000000e+00                 0.0   
1                0.000000e+00                 0.0   
2                0.000000e+00                 0.0   
3                0.000000e+00                 0.0   
4                0.000000e+00                 0.0   
..                        ...                 ...   
943              9.010225e-07                 0.0   
944              3.712580e-04                 0.0   
945              2.102287e-04                 0.0   
946              0.000000e+00                 0.0   
947              0.000000e+00                 0.0   

     RENT COMMUNICATION UTILITIES  RENT  COMMUNICATION  UTILITIES  \
0                        0.009753                        0.000000   
1                        0.000000                        0.041480   
2                        0.000000                        0.000000   
3                        0.006628                        0.000000   
4                        0.000000                        0.042130   
..                            ...                             ...   
943                      0.000000                        0.048933   
944                      0.012022                        0.000000   
945                      0.000000                        0.045710   
946                      0.008217                        0.000000   
947                      0.000000                        0.058566   

     BENEFITS TO FORMER PERSONNEL  NaN  LASTNAME FIRSTNAME        PARTY  \
0                             0.0  0.0  ADERHOLT    ROBERT   Republican   
1                    

Now we need to add a column to represent whether they won or lost in that election year. If they didn't run for reelection that year, it will be NaN. Rows with NaN for the election result will be dropped since they didn't run in the election that year, meaning they aren't relevant to the correlation we are looking into. Some states like NY have the same candidate multiple times under different parties so we also need to handle summing up those counts.

In [25]:
merged_years_df['WIN'] = [0 for i in range(len(merged_years_df))]

def add_victory(row):
    # look up the row in the election data
    thing = election_data.loc[(election_data['last_name'] == row['LASTNAME']) & (election_data['year'] == row['YEAR']) & (election_data['first_name'] == row['FIRSTNAME'])]
    # set win column to 1 if they won
    if len(thing) == 1:
        if thing['totalvotes'].values[0] == 0:
            row['WIN'] = np.nan
        elif float(thing['candidatevotes'].values[0]) / float(thing['totalvotes'].values[0]) >= 0.5:
            row['WIN'] = 1
    elif len(thing) > 1:
        #in some places like NY, you can run in the same race under multiple parties, so we need to add these votes together for our calculation
        total_votes = 0
        for votes in thing['candidatevotes'].values:
            total_votes += votes
        
        if thing['totalvotes'].values[0] == 0:
            row['WIN'] = np.nan
        elif total_votes / float(thing['totalvotes'].values[0]) >= 0.5:
            row['WIN'] = 1
            
    else:
        row['WIN'] = np.nan
    
    return row

victory_df = merged_years_df.apply(add_victory, axis = 1)

#finally drop the rows with NaN in the win column
victory_df.dropna(subset = ['WIN'], inplace=True)
victory_df

BIOGUIDE_ID  YEAR  FRANKED MAIL  PERSONNEL COMPENSATION    TRAVEL  \
0       A000055  2016      0.006792                0.759666  0.062165   
1       A000055  2018      0.003452                0.411295  0.038683   
3       A000367  2016      0.001191                0.845177  0.027990   
4       A000367  2018      0.000342                0.436474  0.015704   
5       A000369  2016      0.001674                0.756212  0.065220   
..          ...   ...           ...                     ...       ...   
942     Y000066  2016      0.048017                0.685941  0.050194   
943     Y000066  2018      0.011930                0.383713  0.027440   
944     Z000017  2016      0.057046                0.734275  0.020706   
945     Z000017  2018      0.019922                0.388718  0.014518   
946     Z000018  2016      0.034226                0.725436  0.106587   

     RENT, COMMUNICATION, UTILITIES  PRINTING AND REPRODUCTION  \
0                          0.067225                   0.007137   
1                          0.000000                   0.003279   
3                          0.064083                   0.002848   
4                          0.000000                   0.001546   
5                          0.084133                   0.002042   
..                              ...                        ...   
942                        0.074791                   0.043196   
943                        0.000000                   0.009136   
944                        0.073223                   0.045088   
945                        0.000000                   0.017221   
946                        0.046623                   0.031469   

     OTHER SERVICES  SUPPLIES AND MATERIALS  EQUIPMENT  ...  \
0          0.023548                0.036877   0.026836  ...   
1          0.009586                0.011584   0.480641  ...   
3          0.030233                0.011010   0.010840  ...   
4          0.013726                0.013396   0.476682  ...   
5          0.044804                0.019708   0.013780  ...   
..              ...                     ...        ...  ...   
942        0.034546                0.041346   0.014895  ...   
943        0.021860                0.011933   0.485055  ...   
944        0.040390                0.012667   0.004211  ...   
945        0.024321                0.016703   0.472676  ...   
946        0.025858                0.010062   0.011522  ...   

     PERSONNEL BENEFITS  RENT COMMUNICATION UTILITIES  \
0                   0.0                      0.009753   
1                   0.0                      0.000000   
3                   0.0                      0.006628   
4                   0.0                      0.000000   
5                   0.0                      0.012427   
..                  ...                           ...   
942                 0.0                      0.007073   
943                 0.0                      0.000000   
944                 0.0                      0.012022   
945                 0.0                      0.000000   
946                 0.0                      0.008217   

     RENT  COMMUNICATION  UTILITIES  BENEFITS TO FORMER PERSONNEL  NaN  \
0                          0.000000                           0.0  0.0   
1                          0.041480                           0.0  0.0   
3                          0.000000                           0.0  0.0   
4                          0.042130                           0.0  0.0   
5                          0.000000                           0.0  0.0   
..                              ...                           ...  ...   
942                        0.000000                           0.0  0.0   
943                        0.048933                           0.0  0.0   
944                        0.000000                           0.0  0.0   
945                        0.045710                           0.0  0.0   
946                        0.000000                           0.0  0.0   

   

Now that the data has been setup with columns representing each expense category as well as election results, we can see if there's a correlation between spending habits and election victory. To do this, I will first start off by training a model on each specific category to see if individual categories correlation with election success.

In [41]:
from sklearn.neighbors import KNeighborsClassifier
import sklearn.model_selection as ms
import sklearn.metrics as met

# use PERSONAL_COMPENSATION for ind and WIN for dep

y = victory_df['WIN']
non_nan = categories[0:len(categories)-1]
for category in non_nan:
    X = victory_df[[category]]
    ind_train, ind_test, dep_train, dep_test = ms.train_test_split(X, y, random_state=40)

    k_range = range(1, 10) # we will try k values from 1 to 10
    k_scores = []
    for k in k_range:
        neighbors = KNeighborsClassifier(n_neighbors=k)
        scores = ms.cross_val_score(neighbors, ind_train, dep_train, cv=10, scoring='accuracy')
        k_scores.append(scores.mean())

    # get the value of k with the highest cross-validated accuracy
    k = k_scores.index(max(k_scores)) + 1

    #train the dataset with the hyperparameter we just found
    neighbors = KNeighborsClassifier(n_neighbors=k)
    neighbors.fit(ind_train, dep_train)

    predicted = neighbors.predict(ind_test)
    acc = met.accuracy_score(dep_test, predicted, normalize=True, sample_weight=None)
    print("Accuracy:", acc)

    actual = np.array(dep_test)
    predictions = np.array(predicted)
    print(category + '\n' + str(met.confusion_matrix(actual, predictions)))

Accuracy: 0.9038461538461539
FRANKED MAIL
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
PERSONNEL COMPENSATION
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
TRAVEL
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
RENT, COMMUNICATION, UTILITIES
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
PRINTING AND REPRODUCTION
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
OTHER SERVICES
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
SUPPLIES AND MATERIALS
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
EQUIPMENT
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
TRANSPORTATION OF THINGS
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
PERSONNEL BENEFITS
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
RENT COMMUNICATION UTILITIES
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
RENT  COMMUNICATION  UTILITIES
[[  0  15]
 [  0 141]]
Accuracy: 0.9038461538461539
BENEFITS TO FORMER PERSONNEL
[[  0  15]
 [  0 141]]
